# Generated by Django 3.0.2 on 2020-02-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_auto_20200202_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
