# Generated by Django 2.2.7 on 2020-02-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0005_auto_20200202_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Lactose_Intolerant',
            field=models.BooleanField(default=False, help_text='Write here your message!'),
        ),
    ]
